"""empty message

Revision ID: acd7aeacd48c
Revises: ff2c6bf38621
Create Date: 2022-08-08 18:52:39.912763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acd7aeacd48c'
down_revision = 'ff2c6bf38621'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist_genre_table', sa.Column('genre_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'artist_genre_table', 'Genre', ['genre_id'], ['id'])
    op.add_column('venue_genre_table', sa.Column('genre_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'venue_genre_table', 'Genre', ['genre_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venue_genre_table', type_='foreignkey')
    op.drop_column('venue_genre_table', 'genre_id')
    op.drop_constraint(None, 'artist_genre_table', type_='foreignkey')
    op.drop_column('artist_genre_table', 'genre_id')
    # ### end Alembic commands ###
